# Generated by Django 3.1.6 on 2022-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0003_auto_20220403_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_price_int',
            field=models.FloatField(default=0),
        ),
    ]
