# Generated by Django 3.1.6 on 2022-04-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0004_auto_20220403_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
    ]
